// <auto-generated />
namespace WebApiNoTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class RelationupdatefromProducttoOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationupdatefromProducttoOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202003030149388_Relation update from Product to Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
